In [1]:
from shape_reader import ShapeReader
import numpy as np

In [2]:
s1=ShapeReader.shape_from_file('mesh3b.off')
s1.prepare()
s1.compute_links()
s1.compute_triple_points()

In [3]:
s1.compute_delaunay_triangles()

In [4]:
s1.compute_gains()

True

In [5]:
s1.V

array([[-0.5,  0. ,  0. ],
       [ 0.5,  0. ,  2. ],
       [ 0. ,  1. ,  0. ],
       [ 0. , -1. ,  0. ],
       [ 0.5, -0.5,  1. ]], dtype=float32)

In [6]:
s1.T

array([[0., 1., 2.],
       [0., 1., 3.],
       [1., 3., 4.],
       [0., 2., 4.]])

In [ ]:
s1.links

In [10]:
verts=s1.polygon_angles[0]

In [9]:
triangles=s1.polygon_triangles[0]

In [17]:
s1.polygon_angles

{0: array([[-0.33333334,  0.16666667,  0.16666667],
        [ 0.33333334,  0.16666667, -0.16666667],
        [ 0.44444445,  0.44444445, -0.22222222],
        [ 0.        ,  0.        , -1.        ],
        [ 0.35555556, -0.17777778, -0.44444445],
        [-0.55172414, -0.27586207,  0.41379312],
        [ 0.33333334, -0.16666667, -0.16666667],
        [-0.33333334, -0.16666667,  0.16666667],
        [-0.44444445, -0.44444445,  0.22222222],
        [-0.        , -0.        ,  1.        ],
        [-0.35555556,  0.17777778,  0.44444445],
        [ 0.55172414,  0.27586207, -0.41379312]]),
 1: array([[ 0.33333334, -0.16666667, -0.16666667],
        [-0.33333334, -0.16666667,  0.16666667],
        [-0.44444445, -0.44444445,  0.22222222],
        [-0.23529412,  0.        ,  0.05882353],
        [-0.46376812, -0.11594203,  0.05797102],
        [ 0.        , -1.60000002,  0.80000001],
        [-0.33333334,  0.16666667,  0.16666667],
        [ 0.33333334,  0.16666667, -0.16666667],
        [ 0.

In [16]:
s1.polygon_triangles

{0: array([[ 2,  7,  4],
        [ 5,  8,  7],
        [ 0,  5,  8],
        [ 0,  9,  8],
        [ 0,  2, 10],
        [11, -1,  2],
        [11,  0,  2],
        [ 0,  9,  8],
        [11,  9, -1],
        [11,  0,  9],
        [ 5,  8, 10],
        [ 0,  5, 10],
        [ 0,  5,  8],
        [-1,  2,  7],
        [11, -1,  2],
        [-1,  7,  4],
        [ 8,  7,  4],
        [11,  8,  7],
        [ 9, -1,  4],
        [11,  9, -1],
        [ 9,  8,  4],
        [11,  9,  8],
        [11,  5,  7],
        [ 6,  2,  7],
        [ 6, 11,  7],
        [ 6, 11,  2],
        [11,  0,  2],
        [11,  0,  5],
        [ 0,  2, 10],
        [ 0,  5, 10]], dtype=int32),
 1: array([[10, -1,  3],
        [ 7, 10, -1],
        [ 7, -1,  9],
        [ 1, -1,  3],
        [ 6, -1,  3],
        [ 6,  7,  9],
        [11,  1, -1],
        [-1,  4,  9],
        [ 1, -1,  4],
        [ 6, -1,  9],
        [11,  6,  9],
        [11,  6, -1],
        [11,  7,  9],
        [ 5, 11,  7],
        [11

In [18]:
s1.polygon_gains

{0: array([[ 0.],
        [ 0.],
        [ 0.],
        [-1.],
        [-1.],
        [ 0.],
        [ 1.],
        [-1.],
        [ 0.],
        [ 1.],
        [ 0.],
        [ 0.],
        [ 0.],
        [-1.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 1.],
        [ 0.],
        [ 0.],
        [-1.],
        [ 0.],
        [-1.],
        [-1.],
        [ 0.],
        [ 1.],
        [ 0.],
        [-1.],
        [ 0.]]),
 1: array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]]),
 2: array([[-1.],
        [ 1.],
        [ 0.],
        [ 1.],
        [ 1.],
        [-1.],

In [11]:
verts

array([[-0.33333334,  0.16666667,  0.16666667],
       [ 0.33333334,  0.16666667, -0.16666667],
       [ 0.44444445,  0.44444445, -0.22222222],
       [ 0.        ,  0.        , -1.        ],
       [ 0.35555556, -0.17777778, -0.44444445],
       [-0.55172414, -0.27586207,  0.41379312],
       [ 0.33333334, -0.16666667, -0.16666667],
       [-0.33333334, -0.16666667,  0.16666667],
       [-0.44444445, -0.44444445,  0.22222222],
       [-0.        , -0.        ,  1.        ],
       [-0.35555556,  0.17777778,  0.44444445],
       [ 0.55172414,  0.27586207, -0.41379312]])

In [12]:
triangles

array([[ 2,  7,  4],
       [ 5,  8,  7],
       [ 0,  5,  8],
       [ 0,  9,  8],
       [ 0,  2, 10],
       [11, -1,  2],
       [11,  0,  2],
       [ 0,  9,  8],
       [11,  9, -1],
       [11,  0,  9],
       [ 5,  8, 10],
       [ 0,  5, 10],
       [ 0,  5,  8],
       [-1,  2,  7],
       [11, -1,  2],
       [-1,  7,  4],
       [ 8,  7,  4],
       [11,  8,  7],
       [ 9, -1,  4],
       [11,  9, -1],
       [ 9,  8,  4],
       [11,  9,  8],
       [11,  5,  7],
       [ 6,  2,  7],
       [ 6, 11,  7],
       [ 6, 11,  2],
       [11,  0,  2],
       [11,  0,  5],
       [ 0,  2, 10],
       [ 0,  5, 10]], dtype=int32)

In [13]:
gains=s1.polygon_gains[0]

In [14]:
gains

array([[ 0.],
       [ 0.],
       [ 0.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [-1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [-1.],
       [ 0.],
       [-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [-1.],
       [ 0.]])

In [7]:
s1.polygon_angles

{0: array([[-0.33333334,  0.16666667,  0.16666667],
        [ 0.33333334,  0.16666667, -0.16666667],
        [ 0.44444445,  0.44444445, -0.22222222],
        [ 0.        ,  0.        , -1.        ],
        [ 0.35555556, -0.17777778, -0.44444445],
        [-0.55172414, -0.27586207,  0.41379312],
        [ 0.33333334, -0.16666667, -0.16666667],
        [-0.33333334, -0.16666667,  0.16666667],
        [-0.44444445, -0.44444445,  0.22222222],
        [-0.        , -0.        ,  1.        ],
        [-0.35555556,  0.17777778,  0.44444445],
        [ 0.55172414,  0.27586207, -0.41379312]]),
 1: array([[ 0.33333334, -0.16666667, -0.16666667],
        [-0.33333334, -0.16666667,  0.16666667],
        [-0.44444445, -0.44444445,  0.22222222],
        [-0.23529412,  0.        ,  0.05882353],
        [-0.46376812, -0.11594203,  0.05797102],
        [ 0.        , -1.60000002,  0.80000001],
        [-0.33333334,  0.16666667,  0.16666667],
        [ 0.33333334,  0.16666667, -0.16666667],
        [ 0.

In [ ]:
s1.polygon_gains