In [6]:
from shape_reader import ShapeReader
import numpy as np
s2=ShapeReader.shape_from_file('octahedron.off')
s2=ShapeReader.shape_from_file('mesh3b.off')
s2=ShapeReader.shape_from_file('a10_sas_50.off')
s2=ShapeReader.shape_from_file('reg_tetra.off')
s2=ShapeReader.shape_from_file('triangle.off')
for i in range(s2.V.shape[0]):
    s2.V[i,:]=s2.V[i,:]/(np.sum(s2.V[i,:]**2)**(0.5))
s2.prepare()
s2.compute_links()
s2.compute_TP_DT_vol4()
s2.compute_gains()
s2.clean_triangles()
s2.orient_polygons()

[0 1 2]
0
[[0 2 3]
 [1 2 3]]
[[-0.52411449  0.52411449  0.67127347]
 [ 0.52411449 -0.52411449 -0.67127347]
 [ 0.32254643  0.85164787 -0.41310988]
 [ 0.47466204 -0.47466204  0.7412098 ]]
[1 0 2]
1
[[0 2 3]
 [1 2 3]]
[[ 0.52411449 -0.52411449 -0.67127347]
 [-0.52411449  0.52411449  0.67127347]
 [ 0.32254653  0.85164784 -0.41310987]
 [-0.83420162 -0.474662   -0.28071998]]
[2 0 1]
2
[[0 2 3]
 [1 2 3]]
[[-0.52411449  0.52411449  0.67127347]
 [ 0.52411449 -0.52411449 -0.67127347]
 [ 0.47466201 -0.47466201  0.74120984]
 [-0.83420156 -0.47466207 -0.28072004]]


In [11]:
'''
The area tests. For a water tight convex (hollow) surface we would expect
total be about 25.132, or 8 pi

For an arbitrary triangle this should be 4 pi
'''
from spherical_integral import *
from ECT_distance import *
import math
sum=0
tol=0.000000000001
for key in s2.clean_polygon_triangles:
    subsum=0
    t=s2.clean_polygon_triangles[key].shape[0]
    for i in range(t):
        #print(i)
        #print(key)
        T1=s2.polygon_angles[key][s2.clean_polygon_triangles[key][i,:],:]
        #paska=R.random()
        #T2=np.matmul(T1,paska.as_matrix())
        p1=T1[0]
        p2=T1[1]
        p3=T1[2]
        #print(T1)
        A=sph_area(p1, p2, p3)
        #print(A)
        #print(s1.clean_polygon_triangles[key][i,:])
        #print(A)
        #print(A)
        sum=sum+A
        subsum=subsum+A
    #print('---')
    print(subsum)
    #print('---')
print(sum)

4.323962956862482
4.323963064241351
3.918444717491653
12.566370738595486
